---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: 'spoke-acm'
  labels:
    cloud: 'auto-detect'
    vendor: 'auto-detect'
    cluster.open-cluster-management.io/clusterset: spoke
spec:
  hubAcceptsClient: true
