FROM alpine:3.19

ARG UID
ENV ANSIBLE_VERSION 11.1.0
ENV ANSIBLE_LINT_VERSION 24.12.0
ENV ANSIBLE_COMM_GENERAL_VERSION 10.1.0
ENV KUBECTL_VERSION 1.32.0

RUN apk --update --no-cache add \
        bash \
        bash-completion \
        ca-certificates \
        fzf \
        git \
        gpg-agent \
        jq \
        openssh-client \
        openssl \
        python3 \
        py3-pip \
        rsync \
        sshpass \
        pass

RUN apk --update add --virtual \
        .build-deps \
        python3-dev \
        libffi-dev \
        openssl-dev \
        build-base \
        curl

# RUN python3 -m ensurepip --upgrade
RUN pip install --upgrade cffi --break-system-packages

RUN pip install --break-system-packages \
        yamllint \
        molecule \
        netaddr \
        kubernetes \
        ansible==${ANSIBLE_VERSION} \
        ansible-lint==${ANSIBLE_LINT_VERSION}

RUN ansible-galaxy collection install \
        community.general:==${ANSIBLE_COMM_GENERAL_VERSION} \
        community.libvirt \
        ansible.posix \
        karmab.kcli \
        kubernetes.core

RUN curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl" --output-dir /usr/bin/ \
  && chmod 755 /usr/bin/kubectl

# script used to init ansible environment
COPY container/ansible-init /usr/bin/
COPY container/.bashrc /root/.bashrc
COPY container/ssh_config /etc/ssh/ssh_config

RUN apk del .build-deps && rm -rf /var/cache/apk/*
RUN adduser -D -H -u ${UID} ansible
RUN git config --global --add safe.directory /ansible

# USER ansible
WORKDIR /ansible
CMD ["/usr/bin/ansible-init"]
