---
- name: 'Install haproxy'
  ansible.builtin.package:
    name: 'haproxy'
    state: 'present'
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - 'dnf'
    - 'packages'
    - 'yum'

- name: 'Allow HAproxy to listen on TCP port 6443'
  community.general.seport:
    ports: 6443
    proto: 'tcp'
    setype: 'http_port_t'
    state: 'present'
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - selinux

- name: 'Discover labs from dnsmasq configuration'
  ansible.builtin.include_tasks:
    file: discover_labs.yaml
    apply:
       tags:
         - 'haproxy'
  when: haproxy_auto_discover_labs | bool
  tags:
    - 'haproxy'

- name: 'Use haproxy_labs if auto-discovery is disabled'
  ansible.builtin.set_fact:
    haproxy_labs_final: "{{ haproxy_labs }}"
  when: not (haproxy_auto_discover_labs | bool)

- name: 'Configure HAproxy for kubernetes'
  ansible.builtin.template:
    src: 'haproxy-k8s.cfg.j2'
    dest: '/etc/haproxy/haproxy.cfg'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'svc reload haproxy'
