---
# Run it with:
#   ap labs/quay/deploy.yaml

- name: 'Import ABI playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  vars:
    lab_name: 'quay'
    lab_node_memory: 32000
    lab_node_disk_data: 60
    start_install: true
    lab_node_network_base: '192.168.129.'
    lab_network_name: 'pinnedis-net'
  tags:
    - 'ocp'

- name: 'Import Quay setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/quay.yaml
  vars:
    lab_name: 'quay'
  tags:
    - 'postinst'
