---
- name: 'Create labs root directory'
  ansible.builtin.file:
    path: "{{ lab_path }}"
    mode: '0755'
    state: 'directory'

- name: 'Create lab directory tree'
  ansible.builtin.file:
    path: "{{ lab_path }}/{{ item }}"
    mode: '0750'
    state: 'directory'
  ignore_errors: "{{ ansible_check_mode }}"
  loop:
    - "{{ lab_name }}"
    - "{{ lab_name }}/config"
    - "{{ lab_name }}/deploy"

- name: 'Include appliance tasks'
  ansible.builtin.include_tasks: appliance.yaml
  when: lab_appliance

- name: 'Create install-config.yaml file'
  ansible.builtin.template:
    src: 'install-config.yaml.j2'
    dest: "{{ lab_path }}/{{ lab_name }}/config/install-config.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Include baremetal tasks'
  ansible.builtin.include_tasks: baremetal.yaml
  when: lab_platform == 'baremetal'
