---
- name: 'Calculate available addresses'
  ansible.builtin.include_tasks:
    file: calculate_addresses.yaml
    apply:
      tags: ['calculate']
  when: lab_auto_addresses | bool
  tags: ['calculate']

- name: 'Create labs root directory'
  ansible.builtin.file:
    path: "{{ lab_path }}"
    mode: '0755'
    state: 'directory'

- name: 'Create lab directory tree'
  ansible.builtin.file:
    path: "{{ lab_path }}/{{ item }}"
    mode: '0750'
    state: 'directory'
  ignore_errors: "{{ ansible_check_mode }}"
  loop:
    - "{{ lab_name }}"
    - "{{ lab_name }}/config"
    - "{{ lab_name }}/deploy"

- name: 'Include appliance tasks'
  ansible.builtin.include_tasks: appliance.yaml
  when: lab_appliance

- name: 'Create install-config.yaml file'
  ansible.builtin.template:
    src: 'install-config.yaml.j2'
    dest: "{{ lab_path }}/{{ lab_name }}/config/install-config.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  no_log: "{{ lab_hide_secrets | bool }}"

- name: 'Create image-based installation config file'
  ansible.builtin.template:
    src: 'image-based-installation-config.yaml.j2'
    dest: "{{ lab_path }}/{{ lab_name }}/config/image-based-installation-config.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  no_log: "{{ lab_hide_secrets | bool }}"
  when: lab_ibi

- name: 'Create image-based config file'
  ansible.builtin.template:
    src: 'image-based-config.yaml.j2'
    dest: "{{ lab_path }}/{{ lab_name }}/config/image-based-config.yaml"
    mode: '0644'
  ignore_errors: "{{ ansible_check_mode }}"
  when: lab_ibi

- name: 'Include baremetal tasks'
  ansible.builtin.include_tasks: baremetal.yaml
  when: lab_platform == 'baremetal'
