---
virt_default_cpus: 12
virt_default_memory: 24000
virt_default_disks: []
virt_default_networks: []
virt_default_net: 'default'
virt_hosts: []
virt_mac_base: '52:54:00:ff:ff:'
virt_networks:
  - {name: 'lab-network', template: 'base', dns: false, dhcp: false, domain: 'local.lab', mac: '52:54:00:97:cc:62', ip: '192.168.126.1/24'}
