---
apiVersion: v1
metadata:
  creationTimestamp: null
  name: ibi-proxy
baseDomain: local.lab
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 192.168.132.0/24
  clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
additionalTrustBundlePolicy: Proxyonly
proxy:
  httpProxy: http://192.168.132.1:3128
  httpsProxy: http://192.168.132.1:3128
  noProxy: ibi-proxy.local.lab,api-int.ibi-proxy.local.lab,192.168.132.0/24,10.132.0.0/14,172.30.0.0/16
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    replicas: 0
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  replicas: 1
platform:
  none: {}
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
