---
- name: 'Create import directory'
  ansible.builtin.file:
    path: "{{ cwd }}"
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'

- name: 'Fetch remote kubeconfig'
  ansible.builtin.fetch:
    dest: '/tmp/'
    src: "{{ kubeconfig }}"
    flat: true
  when: kubeconfig_data is not defined

- name: 'Get kubeconfig data'
  ansible.builtin.set_fact:
    kubeconfig_data: "{{ lookup('file', '/tmp/kubeconfig') }}"
  when: kubeconfig_data is not defined

- name: 'Create managedcluster manifest'
  ansible.builtin.template:
    src: 'managedcluster.yaml.j2'
    dest: "{{ cwd }}/managedcluster-{{ cluster }}.yaml"
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: 'Add default addons'
  ansible.builtin.set_fact:
    addons: "{{ addons | default(ocp_acm_default_addons) }}"
  
- name: 'Add governance addons'
  ansible.builtin.set_fact:
    addons: "{{ addons | union(ocp_acm_governance_addons) }}"
  when: governance | default(false) | bool

- name: 'Create managedclusteraddon manifests'
  ansible.builtin.template:
    src: 'managedclusteraddon.yaml.j2'
    dest: "{{ cwd }}/managedclusteraddon-{{ cluster }}.yaml"
    owner: 'root'
    group: 'root'
    mode: '0640'
  
- name: 'Create import namespace'
  kubernetes.core.k8s:
    name: "{{ cluster }}"
    api_version: v1
    kind: Namespace
    state: present
    # labels:
    #  cluster.open-cluster-management.io/managedCluster: '{{ cluster }}'

- name: 'Create kubeconfig secret'
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: 'v1'
      kind: 'Secret'
      metadata:
        name: 'auto-import-secret'
        namespace: "{{ cluster }}"
      type: 'Opaque'
      stringData:
        autoImportRetry: "5"
      data:
        kubeconfig: "{{ kubeconfig_data | b64encode }}"

- name: 'Apply managedcluster manifest'
  kubernetes.core.k8s:
    state: 'present'
    src: "{{ cwd }}/managedcluster-{{ cluster }}.yaml"
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Apply managedclusteraddon manifests'
  kubernetes.core.k8s:
    state: 'present'
    src: "{{ cwd }}/managedclusteraddon-{{ cluster }}.yaml"
  ignore_errors: "{{ ansible_check_mode }}"
  when: addons | length > 0
