---
- name: 'Extract the auth configuration of an hive cluster'
  hosts:
    - 'lab'

  gather_facts: false

  vars:
    lab_name: ''
    lab_path: '/root/labs'
    hive_cluster_name: ''
    hive_ns: ''

  environment:
    KUBECONFIG: "{{ lab_path }}/{{ lab_name }}/deploy/auth/kubeconfig"

  tasks:
    - name: 'Test lab_name'
      ansible.builtin.fail:
        msg: 'Variable lab_name is empty'
      when: lab_name | length == 0

    - name: 'Test hive_cluster_name'
      ansible.builtin.fail:
        msg: 'Variable hive_cluster_name is empty'
      when: hive_cluster_name | length == 0

    - name: 'Create cluster auth directory'
      ansible.builtin.file:
        path: "{{ lab_path }}/{{ lab_name }}/{{ hive_cluster_name }}/auth"
        mode: '0750'
        state: 'directory'

    - name: 'Wait for kubeconfig'
      kubernetes.core.k8s_info:
        kind: 'Secret'
        name: "{{ hive_cluster_name }}-admin-kubeconfig"
        namespace: "{{ hive_ns }}"
      register: __hive_kubeconfig
      until:
        - __hive_kubeconfig.resources is defined
        - __hive_kubeconfig.resources | length > 0
      retries: 25
      delay: 30

    - name: 'Extract cluster kubeconfig'
      ansible.builtin.command:
        cmd: >
          /usr/local/bin/oc extract -n {{ hive_ns }}
          secret/{{ hive_cluster_name }}-admin-kubeconfig
          --to={{ lab_path }}/{{ lab_name }}/{{ hive_cluster_name }}/auth
          --confirm
        creates: "{{ lab_path }}/{{ lab_name }}/{{ hive_cluster_name }}/auth/kubeconfig"

    - name: 'Wait for the console password'
      kubernetes.core.k8s_info:
        kind: 'Secret'
        name: "{{ hive_cluster_name }}-admin-password"
        namespace: "{{ hive_ns }}"
      register: __hive_kubeadmin
      until:
        - __hive_kubeadmin.resources is defined
        - __hive_kubeadmin.resources | length > 0
      retries: 120
      delay: 30

    - name: 'Extract cluster kubeadmin console password'
      ansible.builtin.command:
        cmd: >
          /usr/local/bin/oc extract -n {{ hive_ns }}
          secret/{{ hive_cluster_name }}-admin-password
          --to={{ lab_path }}/{{ lab_name }}/{{ hive_cluster_name }}/auth
          --confirm
        creates: "{{ lab_path }}/{{ lab_name }}/{{ hive_cluster_name }}/auth/password"
