---
apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: open-cluster-management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: acm-operatorgroup
  namespace: open-cluster-management
spec:
  targetNamespaces:
    - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm
  namespace: open-cluster-management
spec:
  name: advanced-cluster-management
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
