---
# Run it with:
#   ap labs/ovishlit1/deploy.yaml

- name: 'Clean ovishlit1 lab'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'ovishlit1'
  tags:
    - 'clean'
    - 'never'

- name: 'Import ABI playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  tags:
    - 'ocp'
  vars:
    lab_name: 'ovishlit1'
    lab_mac_base: '00:be:ee:11:11:'
    lab_node_network_base: '192.168.131.'
    lab_network_name: 'ovishlit-net'
    lab_abi_ip: "{{ lab_node_network_base }}11"
    lab_api_ips: ["{{ lab_node_network_base }}100"]
    lab_ingress_ips: ["{{ lab_node_network_base }}101"]
    lab_node_memory: 28000
    lab_node_disk_data: 60
    lab_hosts:
      - {id: '11', role: 'master'}
      - {id: '12', role: 'master'}
      - {id: '13', role: 'master'}
    start_install: true

- name: 'Import mce setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/mce.yaml
  tags:
    - 'postinst'
    - 'mce'
  vars:
    lab_name: 'ovishlit1'
    lab_mac_base: '00:be:ee:11:11:'
    lab_node_network_base: '192.168.131.'
    lab_network_name: 'ovishlit-net'
    ocp_apply: false

    ocp_assisted_service_infraenvs:
      - name: 'spoke'
        ns: 'hive-sno'
        ntp: ["{{ lab_node_network_base }}1"]
        redfish: "{{ lab_node_network_base }}1"
        inventory:
          - {'name': "{{ lab_name }}-bmh-1", 'id': '14'}

- name: 'Import hive setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/hive.yml
  tags:
    - 'postinst'
    - 'hive'
  vars:
    lab_name: 'ovishlit1'
    lab_mac_base: '00:be:ee:11:11:'
    lab_node_network_base: '192.168.131.'
    lab_network_name: 'ovishlit-net'
    ocp_apply: false

    ocp_hive_clusters:
      - name: 'spoke'
        ns: 'hive-sno'
        image: 'img4.18.6-x86-64-appsub'
        service_network: '172.32.0.0/16'
        host_network: "{{ lab_node_network_base }}0/24"
        masters: 1
        domain: 'local.lab'
        api_vips: ["{{ lab_node_network_base }}14"]
