apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cnvn-spoke-3
  namespace: default
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [
            {
              "name": "br-ex-network",
              "ips": ["192.168.125.203/24"],
              "gateway": "192.168.125.1"
            }
          ]
    spec:
      domain:
        devices:
          disks:
            - name: vda
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: bridge-net
              bridge: {}
          networkInterfaceMultiqueue: true
        resources:
          requests:
            memory: "16G"
        cpu:
          cores: 12
      networks:
        - name: default
          pod: {}
        - name: bridge-net
          multus:
            networkName: br-ex-network
      volumes:
        - name: vda
          dataVolume:
            name: cnvn-spoke-3
  dataVolumeTemplates:
    - metadata:
        name: cnvn-spoke-3
      spec:
        source:
          blank: {}
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 120Gi
          storageClassName: ocs1-ceph-rbd-virtualization
