---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-ex-network
  namespace: default
spec:
  config: '{
    "cniVersion": "0.4.0",
    "name": "br-ex-network",
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "net-attach-def-name": "default/br-ex-network",
    "mtu": 1500
  }'
