# Warning, this can break the cluster
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: enp3s0-policy
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  desiredState:
    interfaces:
      - name: br-ex
        type: ovs-bridge
        state: up
        bridge:
          port:
            - name: enp3s0
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: enp11s0-bridge-policy
spec:
  # Target the nodes where you want to create the bridge.
  nodeSelector:
    node-role.kubernetes.io/master: ""
  desiredState:
    interfaces:
      # This is the physical interface to be used by the bridge.
      - name: enp11s0
        type: ethernet
        state: up

      # This defines the new Linux bridge named 'br1'.
      - name: br1
        type: linux-bridge
        state: up
        ipv4:
          # The bridge itself gets its IP from DHCP on your physical network.
          enabled: true
          dhcp: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            # Add the physical interface 'enp11s0' as a port on the bridge.
            - name: enp11s0
