---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-manifests
  namespace: spoke1
data:
  99_workload_partitioning.yaml: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: master
      name: 02-master-workload-partitioning
    spec:
      config:
        ignition:
          version: 3.2.0
        storage:
          files:
          - contents:
              source: data:text/plain;charset=utf-8;base64,W2NyaW8ucnVudGltZS53b3JrbG9hZHMubWFuYWdlbWVudF0KYWN0aXZhdGlvbl9hbm5vdGF0aW9uID0gInRhcmdldC53b3JrbG9hZC5vcGVuc2hpZnQuaW8vbWFuYWdlbWVudCIKYW5ub3RhdGlvbl9wcmVmaXggPSAicmVzb3VyY2VzLndvcmtsb2FkLm9wZW5zaGlmdC5pbyIKcmVzb3VyY2VzID0geyAiY3B1c2hhcmVzIiA9IDAsICJjcHVzZXQiID0gIjAtNyIgfQo=
            mode: 420
            overwrite: true
            path: /etc/crio/crio.conf.d/01-workload-partitioning
            user:
              name: root
          - contents:
              source: data:text/plain;charset=utf-8;base64,ewogICJtYW5hZ2VtZW50IjogewogICAgImNwdXNldCI6ICIwLTciCiAgfQp9Cg==
            mode: 420
            overwrite: true
            path: /etc/kubernetes/openshift-workload-pinning
            user:
              name: root
---
apiVersion: v1
kind: Secret
metadata:
  name: pullsecret-cluster-spoke1
  namespace: spoke1
data:
  '.dockerconfigjson': '{"auths":{<redacted>}}'
type: kubernetes.io/dockerconfigjson
---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: spoke1
  namespace: spoke1
spec:
  manifestsConfigMapRef:
    name: extra-manifests
  clusterDeploymentRef:
    name: spoke1
  imageSetRef:
    name: img4.16.0-rc.2-x86-64-appsub
  networking:
    networkType: "OVNKubernetes"
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    serviceNetwork:
      - "172.32.0.0/16"
    machineNetwork:
      - cidr: "192.168.125.0/24"
  provisionRequirements:
    controlPlaneAgents: 1
  sshPublicKey: <redacted>
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: spoke1
  namespace: spoke1
  annotations:
    hive.openshift.io/try-install-once: "true"
spec:
  baseDomain: local.lab
  clusterName: spoke1
  controlPlaneConfig:
    servingCertificates: {}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: spoke1
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "spoke1"
  pullSecretRef:
    name: pullsecret-cluster-spoke1
