---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: assisted-service-ui
  namespace: multicluster-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assisted-service-ui
  template:
    metadata:
      labels:
        app: assisted-service-ui
    spec:
      containers:
        - name: assisted-service-ui
          image: quay.io/edge-infrastructure/assisted-installer-ui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASSISTED_SERVICE_URL
              value: http://assisted-service.multicluster-engine.svc.cluster.local:8090
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: assisted-service-ui
  name: assisted-service-ui
  namespace: multicluster-engine
spec:
  type: ClusterIP
  ports:
  - name: assisted-service-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: assisted-service-ui
