---
# Run it with:
#   ap labs/odf/odf.yaml

- name: 'Clean odf lab'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'odf'
  tags:
    - 'clean'
    - 'never'

- name: 'Import compact playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  tags:
    - 'ocp'
  vars:
    lab_name: 'odf'
    lab_abi_ip: "{{ lab_node_network_base }}11"
    lab_api_ips: ["{{ lab_node_network_base }}110"]
    lab_ingress_ips: ["{{ lab_node_network_base }}111"]
    lab_worker_replicas: 0
    lab_node_memory: 48000
    lab_node_disk_data: 300
    lab_hosts:
      - {id: '11'}
      - {id: '12'}
      - {id: '13'}
    start_install: true

- name: 'Import odf setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/odf.yaml
  tags:
    - 'postinst'
    - 'odf'
  vars:
    lab_name: 'odf'
    ocp_odf_sc_size: '250Gi'
    ocp_odf_storage_nodes:
      - 'odf-node-1'
      - 'odf-node-2'
      - 'odf-node-3'
