---
# Run this with:
#   ap labs/hive-okd/deploy.yaml

- name: 'Clean hive-okd lab'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'okd'
  tags:
    - 'clean'
    - 'never'

- name: 'Import compact playbook'
  ansible.builtin.import_playbook: ../../playbooks/base/compact.yml
  tags:
    - 'ocp'
  vars:
    lab_name: 'okd'
    lab_node_memory: 28000
    lab_node_disk_data: 60
    start_install: true

- name: 'Import HCP setup playbook'
  ansible.builtin.import_playbook: ../../playbooks/setup/hive.yml
  tags:
    - 'postinst'
  vars:
    lab_name: 'okd'
    lab_mac_base: 'be:be:ca:fe:02:'

    ocp_assisted_service_images:
      - ocp_version: '4.13.10'
        arch: 'x86_64'
        version: '413.92.202308210212-0'
      - ocp_version: '4.14.0'
        arch: 'x86_64'
        version: '414.92.202310210434-0'
      - ocp_version: '4.15.0'
        arch: 'x86_64'
        version: '415.92.202402130021-0'

    ocp_assisted_service_infraenvs:
      - name: 'sno'
        ns: 'hive-sno'
        ntp: ['192.168.125.1']
        redfish: '192.168.125.1'
        inventory:
          - {'name': "{{ lab_name }}-bmh-1", 'id': '25'}

    ocp_hive_clusterimagesets:
      - name: 'okd-4.15'
        image: 'registry.ci.openshift.org/origin/release-scos:4.15.0-0.okd-scos-2024-01-18-223523'
        visible: 'true'
      - name: 'okd-4.14'
        image: 'quay.io/okd/scos-release:4.14.0-0.okd-scos-2024-01-30-032525'
        visible: 'true'
      - name: 'okd-4.13'
        image: 'quay.io/okd/scos-release:4.13.0-0.okd-scos-2023-10-19-111256'
        visible: 'true'

    ocp_hive_clusters:
      - name: 'sno'
        ns: 'hive-sno'
        image: 'okd-4.13'
        service_network: '172.32.0.0/16'
        host_network: '192.168.125.0/24'
        masters: 1
        domain: 'local.lab'
        api_vips: ['192.168.125.25']

- name: 'Prepare okd cluster configuration'
  ansible.builtin.import_playbook: ../../playbooks/jobs/hive-config.yml
  vars:
    lab_name: 'okd'
    lab_path: '/root/labs'
    hive_cluster_name: 'sno'
    hive_ns: 'hive-sno'
  tags:
    - 'postinst'
    - 'okd'
    - 'okd-config'
