---
- name: 'Restart dnsmasq service'
  ansible.builtin.service:
    name: 'dnsmasq'
    state: 'restarted'
    enabled: true
  listen: 'svc restart dnsmasq'
  ignore_errors: "{{ ansible_check_mode }}"
