---
lab_abi: False
lab_api_ips: ['192.168.125.10']
lab_appliance: False
lab_appliance_arch: 'x86_64'
lab_appliance_channel: 'stable'
lab_appliance_disk_size: 150
lab_appliance_image: 'quay.io/edge-infrastructure/openshift-appliance'
lab_appliance_local_registry: false
lab_appliance_manifests: []
lab_appliance_operators: []
lab_appliance_version: '4.18.4'
lab_aws_instance_type_master: 'm5.xlarge'
lab_aws_instance_type_worker: 'm5.xlarge'
lab_aws_region: 'us-east-1'
lab_bootstrap_ip: ''
lab_bootstrap_mac: ''
lab_custom_capabilities: []
lab_custom_capability_set: ''
lab_custom_manifests: []
lab_dns_servers: []
lab_gateway: ''
lab_ingress_ips: ['192.168.125.11']
lab_domain: 'local.lab'
lab_fips: False
lab_master_replicas: 3
lab_network_name: 'lab-network'
lab_network_type: 'OVNKubernetes'
lab_node_cpus: 12
lab_node_dhcp: true
lab_node_dhcp6: false
lab_node_disk_data: 1
lab_node_disk_sys: 120
lab_node_disk_pool: 'ocp'
lab_node_ipv4: true
lab_node_ipv6: false
lab_node_memory: 24000
lab_node_network: "{{ lab_node_network_base }}0/24"
lab_node_role: 'master'
lab_ntp_sources: []
lab_mac_base: '52:54:00:ff:ff:'
lab_cluster_network: '10.132.0.0/14'
lab_service_network: '172.30.0.0/16'
lab_path: '/root/labs'
lab_platform: 'baremetal'
lab_proxy_exceptions:
  - "{{ lab_name }}.{{ lab_domain }}"
  - "api-int.{{ lab_name }}.{{ lab_domain }}"
  - "{{ lab_node_network }}"
  - "{{ lab_cluster_network }}"
  - "{{ lab_service_network }}"
lab_proxy_http: ''
lab_worker_replicas: 0
lab_hosts: []
...
