---
apiVersion: v1
metadata:
  creationTimestamp: null
  name: ztvp
baseDomain: <redacted Route53.hosted.zone>
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 10.0.0.0/16
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
compute:
  - name: worker
    architecture: amd64
    hyperthreading: Enabled
    platform:
      aws:
        type: m5.xlarge
    replicas: 0
controlPlane:
  name: master
  architecture: amd64
  hyperthreading: Enabled
  platform:
    aws:
      type: m5.xlarge
  replicas: 3
platform:
  aws:
    region: us-east-1
    vpc: {}
publish: External
additionalTrustBundlePolicy: Proxyonly
pullSecret: '{"auths":{<redacted>}}'
sshKey: <redacted>
