---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: coreos
rendezvousIP: 192.168.129.178
hosts:
  - hostname: coreos-node-1
    interfaces:
      - name: enp7s0
        macAddress: 52:54:00:37:25:d7
    networkConfig:
      interfaces:
        - name: enp3s0
          type: ethernet
          state: up
          mac-address: 52:54:00:00:00:b2
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
        - name: enp7s0
          type: ethernet
          state: up
          mac-address: 52:54:00:37:25:d7
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/sda"
