---
# Run it with:
#   ap labs/ztvp/deploy.yaml

- name: 'Clean ztvp lab'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'ztvp'
  tags:
    - 'clean'
    - 'ztvp-hub'
    - 'never'

- name: 'Clean spoke cluster #1'
  ansible.builtin.import_playbook: ../../playbooks/jobs/clean-lab.yml
  vars:
    lab_name: 'ztvp-spoke-1'
  tags:
    - 'clean'
    - 'ztvp-spoke-1'
    - 'never'

- name: 'Install ZTVP hub cluster'
  ansible.builtin.import_playbook: ../../playbooks/base/abi.yaml
  tags:
    - 'ocp'
    - 'ztvp-hub'
  vars:
    lab_name: 'ztvp'
    lab_abi_ip: "{{ lab_node_network_base }}71"
    lab_api_ips: ["{{ lab_node_network_base }}102"]
    lab_ingress_ips: ["{{ lab_node_network_base }}103"]
    lab_mac_base: 'ce:00:0a:ba:ee:'
    lab_worker_replicas: 0
    lab_node_memory: 22000
    lab_node_disk_data: 60
    lab_hosts:
      - {id: '71'}
      - {id: '72'}
      - {id: '73'}
    lab_custom_capability_set: 'None'
    lab_custom_capabilities:
      - baremetal
      - MachineAPI
      - marketplace
      - OperatorLifecycleManager
      - Console
      - Ingress
      - Storage
      - NodeTuning
      - DeploymentConfig
    start_install: true

- name: 'ZTVP hub cluster post-installation tasks'
  hosts:
    - 'lab'
  gather_facts: false
  tags:
    - 'postinst'
    - 'ztvp-hub'
  vars:
    lab_name: 'ztvp'
    lab_configs: "/root/labs/{{ lab_name }}/config"

  environment:
    KUBECONFIG: "/root/labs/{{ lab_name }}/deploy/auth/kubeconfig"
  roles:
    - 'ocp_lvms'

- name: 'Install hub cluster #1'
  ansible.builtin.import_playbook: ../../playbooks/base/sno.yaml
  vars:
    lab_name: 'ztvp-spoke-1'
    lab_node_cpus: 16
    lab_node_memory: 24000
    start_install: true
    lab_abi_ip: "{{ lab_node_network_base }}75"
    lab_api_ips: ["{{ lab_node_network_base }}75"]
    lab_ingress_ips: ["{{ lab_node_network_base }}75"]
    lab_hosts:
      - {id: '75', iface:'enp1s0'}
    lab_custom_capability_set: 'None'
    lab_custom_capabilities:
      - baremetal
      - MachineAPI
      - marketplace
      - OperatorLifecycleManager
      - Console
      - Ingress
      - Storage
      - NodeTuning
      - DeploymentConfig
  tags:
    - 'ocp'
    - 'ztvp-spoke-1'