---
- name: 'Create ODF installation manifest'
  ansible.builtin.include_role:
    name: 'ocp_olm'
    tasks_from: 'subscription.yaml'
  loop:
    - operator_name: 'odf-operator'
      ns: "{{ ocp_odf_ns }}"
      monitoring: True
      operator_group: 'openshift-storage-operatorgroup'
      source: "{{ ocp_odf_source }}"
  tags: ['olm']

- name: 'Waiting for odf-operator pods'
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        namespace: "{{ ocp_odf_ns }}"
    label_selectors:
      - 'name=ocs-operator'
    wait: yes
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'Create storageclusters'
  ansible.builtin.include_tasks:
    file: 'storageclusters.yaml'
  loop: "{{ ocp_odf_clusters }}"

- name: 'Configure NooBaa'
  ansible.builtin.include_tasks:
    file: 'noobaa.yaml'
  when: ocp_odf_noobaa
