---
- name: Setup Nutanix CAPX environment
  hosts: capx-nutanix

  vars:
    assisted_ingress_ip: '10.89.0.250'
    capi_clusters:
      - name: "{{ nutanix_user }}-ntx-1"
        domain: 'local.lab'
        masters: 3
        workers: 0
        api_vip: "{{ nutanix_net_base }}.173"
        ingress_vip: "{{ nutanix_net_base }}.174"
        memory: '24Gi'
        disk_size: '120Gi'
    capi_install: True
    capi_manifests_path: "/tmp"
    capi_version: v1.7.1
    capi_repo: 'https://github.com/mlorenzofr/cluster-api-agent'
    capi_src_dir: '/tmp/cluster-api-agent'
    # capi_branch: 'cp-new-capabilities'
    capi_branch: 'nutanix-platform'
    cert_manager_version: 'v1.15.1'
    haproxy_k8s_api: False
    haproxy_labs:
      - name: "{{ nutanix_user }}-ntx-1"
        ocp: False
        backends: ["{{ assisted_ingress_ip }}"]
        ingress_hosts:
          - name: 'assisted'
            match: 'assisted-(service|image).assisted-installer.com'
    kind_clusters:
      - name: capi-nutanix-provider
        reinstall: True
        address: "{{ ansible_default_ipv4.address }}"
        nginx: True
        metallb_ip: '10.89.0.250'
    nutanix_api_vip: "{{ nutanix_net_base}}.172"
    nutanix_install: True
    nutanix_csi_install: True
    nutanix_csi_install_src: helm  # or subscription
    nutanix_csi_namespace: 'openshift-cluster-csi-drivers'
    nutanix_csi_sc_name: 'nutanix-volume'
    nutanix_csi_version: 'v2.6.10'
    nutanix_template_name: 'rhcos-4.17.0-x86_64-nutanix.x86_64.qcow2'
    openshift_version: '4.17.0'
    # nutanix_cluster: 'your-cluster-name'
    # nutanix_network: 'ntnx-subnet'
    # nutanix_net_base: '10.0.0'

  roles:
    - role: haproxy
      tags: ['haproxy']
    - role: kind
      tags: ['kind']
    - role: dnsmasq
      tags: ['dnsmasq']

  tasks:
    - name: 'Include os configuration tasks'
      ansible.builtin.import_tasks: tasks/fedora.yaml
      tags:
        - 'os'
        - 'system'

    - name: 'Install cert-manager'
      tags: cert-manager
      block:
        - name: 'Download cert-manager manifest'
          ansible.builtin.get_url:
            url: "https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml"
            dest: '/tmp/cert-manager.yaml'
            owner: 'root'
            group: 'root'
            mode: '0644'
        - name: 'Install cert-manager manifest'
          kubernetes.core.k8s:
            state: 'present'
            src: '/tmp/cert-manager.yaml'
            context: "kind-{{ item.name }}"
          loop: "{{ kind_clusters }}"
        - name: 'Waiting for cert-manager deployment'
          kubernetes.core.k8s:
            context: "kind-{{ item.name }}"
            definition:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cert-manager-webhook
                namespace: cert-manager
            wait: yes
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 600
          loop: "{{ kind_clusters }}"

    - name: 'Install metallb'
      tags: metallb
      block:
        - name: 'Download metallb manifest'
          ansible.builtin.get_url:
            url: "https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml"
            dest: "{{ capi_manifests_path }}/metallb.yaml"
            owner: 'root'
            group: 'root'
            mode: '0644'
        - name: 'Install metallb manifest'
          kubernetes.core.k8s:
            state: 'present'
            src: "{{ capi_manifests_path }}/metallb.yaml"
            context: "kind-{{ item.name }}"
          ignore_errors: "{{ ansible_check_mode }}"
          loop: "{{ kind_clusters }}"
        - name: "Create metallb configuration manifest"
          ansible.builtin.template:
            src: 'templates/metallb-config.yaml.j2'
            dest: "{{ capi_manifests_path }}/metallb-{{ item.name }}-config.yaml"
            owner: 'root'
            group: 'root'
            mode: '0644'
          loop: "{{ kind_clusters }}"
        - name: 'Install metallb-config manifest'
          kubernetes.core.k8s:
            context: "kind-{{ item.name }}"
            state: 'present'
            src: "{{ capi_manifests_path }}/metallb-{{ item.name }}-config.yaml"
          retries: 5
          delay: 30
          loop: "{{ kind_clusters }}"

    - name: 'Install ingress-nginx'
      tags: ingress
      block:
        # - name: 'Download ingress-nginx manifest'
        #   ansible.builtin.get_url:
        #     url: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml'
        #     dest: '/tmp/ingress-nginx.yaml'
        #     owner: 'root'
        #     group: 'root'
        #     mode: '0644'
        - name: 'Copy ingress-nginx manifest'
          ansible.builtin.copy:
            src: 'manifest/nginx.yaml'
            dest: "{{ capi_manifests_path }}/ingress-nginx.yaml"
            owner: 'root'
            group: 'root'
            mode: '0644'
        - name: 'Install ingress-nginx manifest'
          kubernetes.core.k8s:
            state: 'present'
            src: "{{ capi_manifests_path }}/ingress-nginx.yaml"
            context: "kind-{{ item.name }}"
          loop: "{{ kind_clusters }}"
          ignore_errors: "{{ ansible_check_mode }}"

    - name: 'Install infrastructure operator'
      tags:
        - 'infrastructure-operator'
      block:
        - name: 'Create infrastructure operator manifest'
          ansible.builtin.copy:
            src: 'manifest/infrastructure-operator'
            dest: "{{ capi_manifests_path }}"
            owner: 'root'
            group: 'root'
            mode: preserve
        - name: 'Prepare agentconfig'
          ansible.builtin.template:
            src: 'agentconfig.yaml.j2'
            dest: "{{ capi_manifests_path }}/infrastructure-operator/agentconfig-{{ item.name }}.yaml"
            owner: 'root'
            group: 'root'
            mode: '0644'
          loop: "{{ kind_clusters }}"
        - name: 'Check assisted-installer namespace'
          ansible.builtin.command:
            cmd: "kubectl get --context kind-{{ item.name }} ns assisted-installer"
          loop: "{{ kind_clusters }}"
          changed_when: false
          failed_when: false
          register: __assisted_ns
        - name: 'Deploy infrastructure operator resources'
          ansible.builtin.command:
            cmd: "kubectl apply --context kind-{{ kind_clusters[ansible_loop.index0].name }} -k {{ capi_manifests_path }}/infrastructure-operator/"
          loop: "{{ __assisted_ns.results }}"
          loop_control:
            extended: true
          when: item.rc != 0
        - name: 'Create agentconfig resources'
          kubernetes.core.k8s:
            state: 'present'
            src: "{{ capi_manifests_path }}/infrastructure-operator/agentconfig-{{ item.name }}.yaml"
            context: "kind-{{ item.name }}"
          ignore_errors: "{{ ansible_check_mode }}"
          loop: "{{ kind_clusters }}"
        - name: 'Waiting for assisted-service deployment'
          kubernetes.core.k8s:
            context: "kind-{{ item.name }}"
            definition:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: assisted-service
                namespace: assisted-installer
            wait: yes
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 600
          loop: "{{ kind_clusters }}"
          ignore_errors: "{{ ansible_check_mode }}"
          retries: 5
          delay: 30
        - name: 'Waiting for assisted-image pod'
          kubernetes.core.k8s:
            context: "kind-{{ item.name }}"
            definition:
              apiVersion: v1
              kind: Pod
              metadata:
                name: assisted-image-service-0
                namespace: assisted-installer
            wait: yes
            wait_condition:
              type: Ready
              status: "True"
            wait_timeout: 600
          ignore_errors: "{{ ansible_check_mode }}"
          loop: "{{ kind_clusters }}"

    - name: 'CAPI installation'
      when: capi_install
      tags:
        - 'capi'
      block:
        - name: 'Download CAPI code'
          ansible.builtin.git:
            repo: "{{ capi_repo }}"
            dest: "{{ capi_src_dir }}"
            version: "{{ capi_branch }}"
        - name: 'Build images'
          ansible.builtin.command:
            chdir: "{{ capi_src_dir }}"
            cmd: 'setsid make docker-build-all'
          environment:
            CONTAINER_TAG: 'local'
        - name: 'Remove old exported images'
          ansible.builtin.file:
            path: "/tmp/{{ item }}.tar.gz"
            state: 'absent'
          loop:
            - 'controlplane'
            - 'bootstrap'
        - name: 'Save images'
          ansible.builtin.command:
            cmd: "podman save quay.io/edge-infrastructure/openshift-capi-agent-{{ item }}:local -o /tmp/{{ item }}.tar.gz"
          loop:
            - 'controlplane'
            - 'bootstrap'
        - name: 'Load images'
          ansible.builtin.command:
            cmd: "kind load image-archive --name {{ item.0.name }} /tmp/{{ item.1 }}.tar.gz"
          loop: "{{ kind_clusters | product(['controlplane','bootstrap']) | list }}"
#       - name: 'Create controlplane & bootloader manifests'
#         ansible.builtin.shell:
#           chdir: "{{ capi_src_dir }}"
#           cmd: 'make generate && make manifests && make build-installer'
#         environment:
#           CONTAINER_TAG: 'local'
#           DIST_DIR: '/tmp'
#           GOCACHE: '/tmp/.go'
#           HOME: '/tmp'
#           SSH_AUTHORIZED_KEY: "{{ lab_ssh_pubkey }}"
#           PULLSECRET: "{{ lab_pull_secret_b64 }}"

    # The manifests generated by make manifest in the cluster-api-agent project should
    # work, but there is currently an issue with roles and imagePullPolicy (we are
    # using local images), so we use a fixed version of these files
    - name: 'Install CAPI Bootstrap and Control Plane providers'
      tags:
        - 'capi'
      block:
        - name: 'Copy provider manifests'
          ansible.builtin.copy:
            src: 'manifest/{{ item }}_install.yaml'
            dest: "{{ capi_manifests_path }}/{{ item }}_install.yaml"
            owner: 'root'
            group: 'root'
            mode: '0644'
          loop:
            - 'controlplane'
            - 'bootstrap'
        - name: 'Install CAPI providers'
          kubernetes.core.k8s:
            state: 'present'
            src: "{{ capi_manifests_path }}/{{ item.1 }}_install.yaml"
            context: "kind-{{ item.0.name }}"
          ignore_errors: "{{ ansible_check_mode }}"
          loop: "{{ kind_clusters | product(['controlplane','bootstrap']) | list }}"

    - name: 'Install nutanix infrastructure provider'
      when: nutanix_install
      ansible.builtin.command:
        cmd: "clusterctl init --kubeconfig-context kind-{{ item.name }} --core cluster-api:v1.9.3 --bootstrap - --control-plane - --infrastructure nutanix"
      environment:
        NUTANIX_ENDPOINT: "{{ nutanix_prism_central }}"
        NUTANIX_USER: "{{ nutanix_user }}"
        NUTANIX_PASSWORD: "{{ nutanix_password }}"
        NUTANIX_INSECURE: true  # or false
        KUBERNETES_VERSION: "{{ openshift_version }}"
        # WORKER_MACHINE_COUNT: 0
        NUTANIX_SSH_AUTHORIZED_KEY: "{{ lab_ssh_pubkey }}"
        NUTANIX_PRISM_ELEMENT_CLUSTER_NAME: "{{ nutanix_cluster }}"
        NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME: "{{ nutanix_template_name }}"
        NUTANIX_SUBNET_NAME: "{{ nutanix_network }}"
        CONTROL_PLANE_ENDPOINT_IP: "{{ nutanix_api_vip }}"
      loop: "{{ kind_clusters }}"
      tags:
        - 'capx'

    - name: 'Create CAPI clusters'
      ansible.builtin.include_tasks: tasks/capi_cluster.yaml
      tags:
        - 'capi-cluster'
        - 'never'
      loop: "{{ capi_clusters }}"

    - name: 'Install Nutanix CSI Operator in workload cluster (CAPI)'
      when: nutanix_csi_install
      tags:
        - 'csi'
        - 'never'
      block:
        - name: 'Set the Nutanix CSI installation source template'
          ansible.builtin.set_fact:
            __nutanix_csi_template_src: 'nutanix-csi-crs.yaml.j2'
          when: nutanix_csi_install_src == "helm"
        - name: 'Set the Nutanix CSI installation source template'
          ansible.builtin.set_fact:
            __nutanix_csi_template_src: 'crs-csi-operator.yaml.j2'
          when: nutanix_csi_install_src == "subscription"
        - name: 'Create CSI installation template'
          ansible.builtin.template:
            src: 'templates/{{ __nutanix_csi_template_src }}'
            dest: "{{ capi_manifests_path }}/nutanix-csi-crs.yaml"
            owner: 'root'
            group: 'root'
            mode: '0600'
        - name: 'Install cluster manifest'
          kubernetes.core.k8s:
            state: 'present'
            src: "{{ capi_manifests_path }}/nutanix-csi-crs.yaml"

    - name: 'Nutanix CSI Operator day-2 tasks'
      ansible.builtin.include_tasks: tasks/csi.yaml
      loop: "{{ capi_clusters }}"
      when: nutanix_csi_install
      tags:
        - 'csi-day-2'
        - 'never'
