---
galaxy_info:
  role_name: beaker_lab
  namespace: mlorenzofr
  author: 'Manuel Lorenzo'
  description: 'Manage new Openshift labs on a beaker machine'
  company: 'Red Hat'
  license: 'MIT'
  min_ansible_version: '2.12'
  platforms:
    - name: 'EL'
      versions:
        - '8'
        - '9'
  galaxy_tags: []
dependencies: []
