---
- name: 'Restart libvirtd service'
  ansible.builtin.service:
    name: 'libvirtd'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 8
  listen: 'svc restart libvirtd'

- name: 'Restart virtqemud service'
  ansible.builtin.service:
    name: 'virtqemud'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 9'
  listen:
    - 'svc restart libvirtd'
    - 'svc restart virtqemud'

- name: 'Restart virtnetworkd service'
  ansible.builtin.service:
    name: 'virtnetworkd'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 9'
  listen:
    - 'svc restart libvirtd'
    - 'svc restart virtnetworkd'

- name: 'Restart virtnodedevd service'
  ansible.builtin.service:
    name: 'virtnodedevd'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 9'
  listen:
    - 'svc restart libvirtd'
    - 'svc restart virtnodedevd'

- name: 'Restart virtnwfilterd service'
  ansible.builtin.service:
    name: 'virtnwfilterd'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 9'
  listen:
    - 'svc restart libvirtd'
    - 'svc restart virtnwfilterd'

- name: 'Restart virtsecretd service'
  ansible.builtin.service:
    name: 'virtsecretd'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 9'
  listen:
    - 'svc restart libvirtd'
    - 'svc restart virtsecretd'

- name: 'Restart virtinterfaced service'
  ansible.builtin.service:
    name: 'virtinterfaced'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 9'
  listen:
    - 'svc restart libvirtd'
    - 'svc restart virtinterfaced'

- name: 'Restart virtstoraged service'
  ansible.builtin.service:
    name: 'virtstoraged'
    state: 'restarted'
    enabled: true
  when: ansible_distribution_major_version == 9'
  listen:
    - 'svc restart libvirtd'
    - 'svc restart virtstoraged'
