---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: acm-bmh-1
  namespace: spoke
  labels:
    infraenvs.agent-install.openshift.io: spoke-acm
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: acm-bmh-1
spec:
  automatedCleaningMode: disabled
  bootMACAddress: be:be:ca:fe:02:64
  online: true
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    disableCertificateVerification: True
    address: redfish-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/acm-bmh-1
    credentialsName: acm-bmh-1-bmc-secret
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: acm-bmh-2
  namespace: spoke
  labels:
    infraenvs.agent-install.openshift.io: spoke-acm
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: acm-bmh-2
spec:
  automatedCleaningMode: disabled
  bootMACAddress: be:be:ca:fe:02:65
  online: true
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    disableCertificateVerification: True
    address: redfish-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/acm-bmh-2
    credentialsName: acm-bmh-2-bmc-secret
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: acm-bmh-3
  namespace: spoke
  labels:
    infraenvs.agent-install.openshift.io: spoke-acm
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: acm-bmh-3
spec:
  automatedCleaningMode: disabled
  bootMACAddress: be:be:ca:fe:02:66
  online: true
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    disableCertificateVerification: True
    address: redfish-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/acm-bmh-3
    credentialsName: acm-bmh-3-bmc-secret
